Updated callback to route messages to AWS Connect queue for routing into NYS call center
covid-alert-ny/covid-green-regional-lambdas pull request #4
Opened 2020-08-12 18:06 UTC by dennisgove

2020-08-12 20:11 UTC, dennisgove commented
A few changes have come out of a discussion with Jesse at AWS.

In our initial conversations they weren't aware that we had a lambda already. What they suggested at first can be simplified a lot because we're running inside a lambda. Instead of hitting a HTTP endpoint we can actually add the callback to New York State's callback connect process directly. We don't need to go through this extra authentication and HTTP hop.

Jesse is sending me sample code for adding a call directly to the Connect API. We looked at it together and it's very straight forward.

2020-08-14 17:34 UTC, segfault requested changes
looks good. small typo to fix up

2020-08-14 17:34 UTC, segfault commented on utils.js
> +      awsConnectCrossAccountExternalId: process.env.AWS_CONNECT_CROSS_ACCOUNT_EXTERNAL_ID,
Looks like a typo here `process.env.AWS_CONNECT_CROSS_ACCOUNT_ROLE_SESSIOON_NAME`

2020-08-14 17:34 UTC, segfault commented on README.md
> +| `AWS_CONNECT_CROSS_ACCOUNT_ROLE_SESSIOON_NAME` | `awsPostCallback` | `awsConnectCrossAccountRoleSessionName` | ?? |
s/SESSIOON/SESSION/

2020-08-17 14:10 UTC, merged